fernandes:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.akefvzi.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: spring-cleanarch
